replicaCount: 1

image:
  repository: ippendigital/virtrualizer
  pullPolicy: IfNotPresent
  tag: v1.0.0

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: id-docker

persistentVolume:
  create: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: true
  annotations: {}
  path: "/"

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 9
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}