apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtualizer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "virtualizer.name" . }}
    helm.sh/chart: {{ include "virtualizer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "prometheus.io/scrape": "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "virtualizer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

